# Generated by Django 4.1 on 2022-09-08 11:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='main_content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=None),
        ),
    ]
