# Generated by Django 4.1 on 2022-09-08 11:33

from django.db import migrations
import streamfieldblocks.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_main_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='main_content',
            field=wagtail.fields.StreamField([('responsive_image', streamfieldblocks.models.ResponsiveImageBlock()), ('card', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.TextBlock()), ('page_link', wagtail.blocks.PageChooserBlock())]))], blank=True, use_json_field=None),
        ),
    ]
