# Generated by Django 4.1 on 2022-09-08 17:34

from django.db import migrations, models
import django.db.models.deletion
import streamfieldblocks.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('project_title', models.CharField(max_length=150)),
                ('date', models.DateField(verbose_name='Article Date')),
                ('content', wagtail.fields.StreamField([('richtext', wagtail.blocks.StructBlock([('richtext', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul']))])), ('carousel', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('flush_list', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.TextBlock(help_text="List item's body text.")))])), ('responsive_image', streamfieldblocks.models.ResponsiveImageBlock())], blank=True, null=True, use_json_field=None)),
                ('testimonials', models.ForeignKey(blank=True, help_text='Project Testimonials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.testimonial')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline_text', models.CharField(blank=True, help_text='Blog listing page header text.', max_length=70)),
                ('experience', wagtail.fields.StreamField([('Timeline_Block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('text', wagtail.blocks.TextBlock()), ('date', wagtail.blocks.DateBlock())]))], blank=True, null=True, use_json_field=None)),
                ('intro', models.TextField()),
                ('background_image', models.ForeignKey(help_text='Header background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image', models.ForeignKey(help_text='Project Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
